#!/bin/bash
# -----------------------------------------------------------------------------
# RMAN 数据库完全恢复脚本
# 目的: 恢复 EPORTDB 数据库，包括控制文件恢复、数据文件重定位、
#       数据库恢复到最新状态并重置日志。
# 作者: Alaia
# 日期: $(date +%F)
# -----------------------------------------------------------------------------

source /home/oracle/.bash_profile

echo "INFO: ORACLE_HOME: $ORACLE_HOME"
echo "INFO: ORACLE_SID: $ORACLE_SID"

DBID="3080101081"
CATALOG_BACKUP_PIECE="/backup_2024/EPORTDB/"
CONTROLFILE_BACKUP_PIECE="${CATALOG_BACKUP_PIECE}EPORTDB_5t4b9ih6_1_1"
NEW_DATAFILE_BASE_PATH="/u01/app/oracle/oradata/eportdb"
RMAN_LOG_DIR="/home/oracle/backupcmd"
RMAN_LOG_FILE="${RMAN_LOG_DIR}/eportdb_all_data_recovery_$(date +%Y%m%d_%H%M%S).log" # 每次生成新日志文件

mkdir -p "$RMAN_LOG_DIR"
if [ ! -d "$RMAN_LOG_DIR" ]; then
	echo "ERROR: RMAN 日志目录 $RMAN_LOG_DIR 不存在或无法创建！"
	exit 1
fi

echo "---------------------------------------------------------" | tee -a "$RMAN_LOG_FILE"
echo "开始数据库恢复进程..." | tee -a "$RMAN_LOG_FILE"
echo "日志文件: $RMAN_LOG_FILE" | tee -a "$RMAN_LOG_FILE"
echo "---------------------------------------------------------" | tee -a "$RMAN_LOG_FILE"

echo set on
rman TARGET / LOG="${RMAN_LOG_FILE}" <<EOF
CONNECT TARGET /;
STARTUP NOMOUNT FORCE;
SET DBID ${DBID};
RESTORE CONTROLFILE FROM '${CONTROLFILE_BACKUP_PIECE}';
SQL 'ALTER DATABASE MOUNT';
catalog start with '${CATALOG_BACKUP_PIECE}' NOPROMPT;
RUN {
  SET NEWNAME FOR DATAFILE 1 TO '${NEW_DATAFILE_BASE_PATH}/system.dbf';
  SET NEWNAME FOR DATAFILE 2 TO '${NEW_DATAFILE_BASE_PATH}/h2010data01.dbf';
  SET NEWNAME FOR DATAFILE 3 TO '${NEW_DATAFILE_BASE_PATH}/sysaux.dbf';
  SET NEWNAME FOR DATAFILE 4 TO '${NEW_DATAFILE_BASE_PATH}/undotbs1.dbf';
  SET NEWNAME FOR DATAFILE 5 TO '${NEW_DATAFILE_BASE_PATH}/yw01.dbf';
  SET NEWNAME FOR DATAFILE 6 TO '${NEW_DATAFILE_BASE_PATH}/users.dbf';
  SET NEWNAME FOR DATAFILE 7 TO '${NEW_DATAFILE_BASE_PATH}/h2010data02.dbf';
  SET NEWNAME FOR DATAFILE 8 TO '${NEW_DATAFILE_BASE_PATH}/h2010data03.dbf';
  SET NEWNAME FOR DATAFILE 9 TO '${NEW_DATAFILE_BASE_PATH}/yw02.dbf';
  SET NEWNAME FOR DATAFILE 10 TO '${NEW_DATAFILE_BASE_PATH}/gps01.dbf';
  SET NEWNAME FOR DATAFILE 11 TO '${NEW_DATAFILE_BASE_PATH}/gps02.dbf';
  SET NEWNAME FOR DATAFILE 12 TO '${NEW_DATAFILE_BASE_PATH}/yw03.dbf';
  SET NEWNAME FOR DATAFILE 13 TO '${NEW_DATAFILE_BASE_PATH}/gps03.dbf';
  SET NEWNAME FOR DATAFILE 14 TO '${NEW_DATAFILE_BASE_PATH}/yw04.dbf';
  SET NEWNAME FOR DATAFILE 15 TO '${NEW_DATAFILE_BASE_PATH}/yw05.dbf';
  SET NEWNAME FOR DATAFILE 16 TO '${NEW_DATAFILE_BASE_PATH}/yw06.dbf';
  SET NEWNAME FOR DATAFILE 17 TO '${NEW_DATAFILE_BASE_PATH}/undotbs2.dbf';
  SET NEWNAME FOR DATAFILE 18 TO '${NEW_DATAFILE_BASE_PATH}/yw07.dbf';
  SET NEWNAME FOR DATAFILE 19 TO '${NEW_DATAFILE_BASE_PATH}/interchange.dbf';
  SET NEWNAME FOR DATAFILE 20 TO '${NEW_DATAFILE_BASE_PATH}/dxp.dbf';
  SET NEWNAME FOR DATAFILE 21 TO '${NEW_DATAFILE_BASE_PATH}/dxp_interchange.dbf';
  SET NEWNAME FOR DATAFILE 22 TO '${NEW_DATAFILE_BASE_PATH}/xd_data_work.dbf';
  SET NEWNAME FOR DATAFILE 23 TO '${NEW_DATAFILE_BASE_PATH}/xd_index_work.dbf';
  SET NEWNAME FOR DATAFILE 24 TO '${NEW_DATAFILE_BASE_PATH}/xd_lob_work.dbf';
  SET NEWNAME FOR DATAFILE 25 TO '${NEW_DATAFILE_BASE_PATH}/sntl_data_work.dbf';
  SET NEWNAME FOR DATAFILE 26 TO '${NEW_DATAFILE_BASE_PATH}/sntl_dico_work.dbf';
  SET NEWNAME FOR DATAFILE 27 TO '${NEW_DATAFILE_BASE_PATH}/sntl_index_work.dbf';
  SET NEWNAME FOR DATAFILE 28 TO '${NEW_DATAFILE_BASE_PATH}/sntl_webdashboard.dbf';
  SET NEWNAME FOR DATAFILE 29 TO '${NEW_DATAFILE_BASE_PATH}/yw08.dbf';
  SET NEWNAME FOR DATAFILE 30 TO '${NEW_DATAFILE_BASE_PATH}/yw09.dbf';
  SET NEWNAME FOR DATAFILE 31 TO '${NEW_DATAFILE_BASE_PATH}/yw10.dbf';
  SET NEWNAME FOR DATAFILE 32 TO '${NEW_DATAFILE_BASE_PATH}/yw11.dbf';
  SET NEWNAME FOR DATAFILE 33 TO '${NEW_DATAFILE_BASE_PATH}/yw12.dbf';
  SET NEWNAME FOR DATAFILE 34 TO '${NEW_DATAFILE_BASE_PATH}/yw13.dbf';
  SET NEWNAME FOR DATAFILE 35 TO '${NEW_DATAFILE_BASE_PATH}/yw14.dbf';
  SET NEWNAME FOR DATAFILE 36 TO '${NEW_DATAFILE_BASE_PATH}/yw15.dbf';
  SET NEWNAME FOR DATAFILE 37 TO '${NEW_DATAFILE_BASE_PATH}/yw16.dbf';
  SET NEWNAME FOR DATAFILE 38 TO '${NEW_DATAFILE_BASE_PATH}/yw17.dbf';
  SET NEWNAME FOR DATAFILE 39 TO '${NEW_DATAFILE_BASE_PATH}/yw18.dbf';
  SET NEWNAME FOR DATAFILE 40 TO '${NEW_DATAFILE_BASE_PATH}/yw19.dbf';
  SET NEWNAME FOR DATAFILE 41 TO '${NEW_DATAFILE_BASE_PATH}/yw20.dbf';
  SET NEWNAME FOR DATAFILE 42 TO '${NEW_DATAFILE_BASE_PATH}/sjjh.dbf';
  SET NEWNAME FOR DATAFILE 43 TO '${NEW_DATAFILE_BASE_PATH}/undotbs3.dbf';
  SET NEWNAME FOR DATAFILE 44 TO '${NEW_DATAFILE_BASE_PATH}/undotbs4.dbf';
  SET NEWNAME FOR DATAFILE 45 TO '${NEW_DATAFILE_BASE_PATH}/ceb01.dbf';
  SET NEWNAME FOR DATAFILE 46 TO '${NEW_DATAFILE_BASE_PATH}/ceb02.dbf';
  SET NEWNAME FOR DATAFILE 47 TO '${NEW_DATAFILE_BASE_PATH}/ceb03.dbf';
  SET NEWNAME FOR DATAFILE 48 TO '${NEW_DATAFILE_BASE_PATH}/ceb04.dbf';
  SET NEWNAME FOR DATAFILE 49 TO '${NEW_DATAFILE_BASE_PATH}/ceb05.dbf';
  SET NEWNAME FOR DATAFILE 50 TO '${NEW_DATAFILE_BASE_PATH}/ceb06.dbf';
  SET NEWNAME FOR DATAFILE 51 TO '${NEW_DATAFILE_BASE_PATH}/ceb07.dbf';
  SET NEWNAME FOR DATAFILE 52 TO '${NEW_DATAFILE_BASE_PATH}/ceb08.dbf';
  SET NEWNAME FOR DATAFILE 53 TO '${NEW_DATAFILE_BASE_PATH}/ceb09.dbf';
  SET NEWNAME FOR DATAFILE 54 TO '${NEW_DATAFILE_BASE_PATH}/ceb10.dbf';
  SET NEWNAME FOR DATAFILE 55 TO '${NEW_DATAFILE_BASE_PATH}/ceb11.dbf';
  SET NEWNAME FOR DATAFILE 56 TO '${NEW_DATAFILE_BASE_PATH}/ceb12.dbf';
  SET NEWNAME FOR DATAFILE 57 TO '${NEW_DATAFILE_BASE_PATH}/ceb13.dbf';
  SET NEWNAME FOR DATAFILE 58 TO '${NEW_DATAFILE_BASE_PATH}/ceb14.dbf';
  SET NEWNAME FOR DATAFILE 59 TO '${NEW_DATAFILE_BASE_PATH}/ceb15.dbf';
  SET NEWNAME FOR DATAFILE 60 TO '${NEW_DATAFILE_BASE_PATH}/ceb16.dbf';
  SET NEWNAME FOR DATAFILE 61 TO '${NEW_DATAFILE_BASE_PATH}/yw21.dbf';
  SET NEWNAME FOR DATAFILE 62 TO '${NEW_DATAFILE_BASE_PATH}/yw22.dbf';
  SET NEWNAME FOR DATAFILE 63 TO '${NEW_DATAFILE_BASE_PATH}/h2010data04.dbf';
  SET NEWNAME FOR DATAFILE 64 TO '${NEW_DATAFILE_BASE_PATH}/h2010data05.dbf';
  SET NEWNAME FOR DATAFILE 65 TO '${NEW_DATAFILE_BASE_PATH}/yw23.dbf';
  SET NEWNAME FOR DATAFILE 66 TO '${NEW_DATAFILE_BASE_PATH}/yw24.dbf';
  SET NEWNAME FOR DATAFILE 67 TO '${NEW_DATAFILE_BASE_PATH}/yw25.dbf';
  SET NEWNAME FOR DATAFILE 68 TO '${NEW_DATAFILE_BASE_PATH}/ksdsly.dbf';
  SET NEWNAME FOR DATAFILE 69 TO '${NEW_DATAFILE_BASE_PATH}/alskdev.dbf';
  SET NEWNAME FOR DATAFILE 70 TO '${NEW_DATAFILE_BASE_PATH}/tscloudgate.dbf';
  SET NEWNAME FOR DATAFILE 71 TO '${NEW_DATAFILE_BASE_PATH}/yw26.dbf';
  SET NEWNAME FOR DATAFILE 72 TO '${NEW_DATAFILE_BASE_PATH}/yw27.dbf';
  SET NEWNAME FOR DATAFILE 73 TO '${NEW_DATAFILE_BASE_PATH}/yw28.dbf';
  SET NEWNAME FOR DATAFILE 74 TO '${NEW_DATAFILE_BASE_PATH}/yw29.dbf';
  SET NEWNAME FOR DATAFILE 75 TO '${NEW_DATAFILE_BASE_PATH}/yw30.dbf';
  SET NEWNAME FOR DATAFILE 76 TO '${NEW_DATAFILE_BASE_PATH}/yw31.dbf';
  SET NEWNAME FOR DATAFILE 77 TO '${NEW_DATAFILE_BASE_PATH}/yw32.dbf';
  SET NEWNAME FOR DATAFILE 78 TO '${NEW_DATAFILE_BASE_PATH}/yw33.dbf';
  SET NEWNAME FOR DATAFILE 79 TO '${NEW_DATAFILE_BASE_PATH}/yw34.dbf';
  SET NEWNAME FOR DATAFILE 80 TO '${NEW_DATAFILE_BASE_PATH}/wms01.dbf';
  SET NEWNAME FOR DATAFILE 81 TO '${NEW_DATAFILE_BASE_PATH}/yw35.dbf';
  SET NEWNAME FOR DATAFILE 82 TO '${NEW_DATAFILE_BASE_PATH}/wmsclient.dbf';
  SET NEWNAME FOR DATAFILE 83 TO '${NEW_DATAFILE_BASE_PATH}/rway01.dbf';
  SET NEWNAME FOR DATAFILE 84 TO '${NEW_DATAFILE_BASE_PATH}/h2010data06.dbf';
  SET NEWNAME FOR DATAFILE 85 TO '${NEW_DATAFILE_BASE_PATH}/h2010data07.dbf';
  SET NEWNAME FOR DATAFILE 86 TO '${NEW_DATAFILE_BASE_PATH}/h2010data08.dbf';
  SET NEWNAME FOR DATAFILE 87 TO '${NEW_DATAFILE_BASE_PATH}/airport01.dbf';
  SET NEWNAME FOR DATAFILE 88 TO '${NEW_DATAFILE_BASE_PATH}/dbtest01.dbf';
  RESTORE DATABASE;
  SWITCH DATAFILE ALL;
}
EXIT;
EOF

echo "---------------------------------------------------------" | tee -a "$RMAN_LOG_FILE"
echo "RMAN 数据库恢复脚本执行成功！请查看数据库运行状态和日志文件。" | tee -a "$RMAN_LOG_FILE"
echo "---------------------------------------------------------" | tee -a "$RMAN_LOG_FILE"

